package evil

import (
	"bytes"
	"go/ast"
	"log"
	"maps"
)

const metaMainTemplate = `
// Code generated by evil. DO NOT EDIT.
// go:build ignore

package main

import (
	__evil__ "github.com/phaezer/evil"
	{{ if .ImportName }} "{{ .ImportName }}" {{ end }}
)

func main() {
	g := __evil__.NewGenerator()

	{{ range $func := .Funcs }}
	{{ $func(g) }}
	{{ end }}
}
`

type MetaGenerator struct {
	*Generator

	buf bytes.Buffer

	target string

	funcs map[string][]*ast.FuncDecl
}

// todo: determine the output file depending on if it's a main package or not
//  then open the file to write to

func NewMetaGenerator(filename string) *MetaGenerator {
	mg := &MetaGenerator{
		Generator: NewGenerator(),
		funcs:     make(map[string][]*ast.FuncDecl),
	}

	mg.Generator.loadFile(filename)

	importName := mg.loadFile(filename).ImportName()

	// find all functions in the target file that match the signature
	for f := range maps.Values(mg.files) {
		for fn := range iterAstDeclsForType[*ast.FuncDecl](f.ast.Decls) {
			if fn.Type.Params == nil {
				continue
			}

			// must have exactly one type parameter
			if fn.Type.Params.NumFields() != 1 {
				continue
			}

			field := fn.Type.Params.List[0]

			// must be a ptr to the generator struct
			if _, ok := field.Type.(*ast.SelectorExpr); !ok {
				continue
			}

			sel := field.Type.(*ast.SelectorExpr)
			if sel.X.(*ast.Ident).Name == importName && sel.Sel.Name == "Generator" {
				mg.funcs[f.filename] = append(mg.funcs[f.filename], fn)
			}

			for _, ident := range field.Names {
				log.Printf("ident = %#v\n", ident)
			}
		}
	}

	return mg
}

// todo: use a template string to generate the file
func (mg *MetaGenerator) writeFunc(fn *ast.FuncDecl) {

}
